#!/usr/bin/env sh

# args :
#
#   (docker exec -it container)* python -m pyls

cmd="$PROJECT_PYTHON_LSP"

ssh "$HOST_USER@$HOST_IP" -p "$HOST_PORT" -tt "$cmd" > /tmp/pyls.out &
PID="$!"

while kill -0 "$PID"; do
    cat /tmp/pyls.out
done
